<script setup>
import { ref, onMounted } from 'vue'
import BaseTable from '../components/common/BaseTable.vue'

const columns = [
  { key: 'status', title: 'STATUS', width: '120px', render: 'status' },
  { key: 'createdAt', title: 'CREATED AT', width: '200px', render: 'timestamp' },
  { key: 'fileName', title: 'FILE NAME' },
  { key: 'fileType', title: 'FILE TYPE', width: '150px' },
  { key: 'delivery', title: 'DELIVERY' },
  { key: 'actions', title: 'ACTIONS', width: '180px' }
]

const items = ref([])

function formatDate(d) {
  if (!d) return ''
  try { return new Date(d).toLocaleString() } catch { return String(d) }
}

async function loadFiles() {
  try {
    const res = await fetch('/api/File/latest?count=50')
    if (res.ok) {
      const data = await res.json()
      items.value = (data || []).map(i => ({
        id: i.filE_ID ?? i.FILE_ID,
        status: i.ruN?.ruN_STATUS?.ruN_STATUS1 ?? i.RUN?.RUN_STATUS?.RUN_STATUS1 ?? 'unknown',
        createdAt: formatDate(i.createD_AT ?? i.CREATED_AT),
        fileName: i.filE_NAME ?? i.FILE_NAME ?? '',
        fileType: i.filE_TYPE?.filE_TYPE_NAME ?? i.FILE_TYPE?.FILE_TYPE_NAME ?? 'N/A',
        delivery: i.ruN?.deliverY_METHOD?.deliverY_METHOD1 ?? i.RUN?.DELIVERY_METHOD?.DELIVERY_METHOD1 ?? 'N/A',
        emailStatus: i.ruN?.emaiL_STATUS?.emaiL_STATUS1 ?? i.RUN?.EMAIL_STATUS?.EMAIL_STATUS1 ?? 'N/A',
        actions: ''
      }))
      return
    }
  } catch (e) {
    console.error('Failed to load files repo', e)
  }

  // sample placeholder rows
  items.value = [
    { status: 'ok', createdAt: formatDate('2025-10-15T11:23:04'), fileName: '32_Ali_Hassan.xml', fileType: 'XML', delivery: 'Email to ali@acme.com', actions: '' },
    { status: 'error', createdAt: formatDate('2025-10-15T11:20:10'), fileName: '12_Sarah_Ahmed.xml', fileType: 'XML', delivery: 'Manual review required', actions: '' },
    { status: 'ok', createdAt: formatDate('2025-10-14T09:05:30'), fileName: '18_Dana_Maohammed.xml', fileType: 'XML', delivery: 'Downloaded', actions: '' }
  ]
}

onMounted(() => { loadFiles() })

const filters = [
  { key: 'status', label: 'Status', type: 'select', options: [
    { value: '', label: 'Any' },
    { value: 'COMPLETED', label: 'Completed' },
    { value: 'FAILED', label: 'Failed' },
    { value: 'PENDING', label: 'Pending' }
  ], default: '' },
  { key: 'fileType', label: 'File Type', type: 'select', options: [
    { value: '', label: 'Any' },
    { value: 'XML', label: 'XML' },
    { value: 'CSV', label: 'CSV' },
    { value: 'JSON', label: 'JSON' }
  ], default: '' },
  { key: 'delivery', label: 'Delivery', type: 'select', options: [
    { value: '', label: 'Any' },
    { value: 'Email', label: 'Email' },
    { value: 'Downloaded', label: 'Downloaded' },
    { value: 'Manual', label: 'Manual' }
  ], default: '' },
  { key: 'createdAt', label: 'Date', type: 'date' }
]

function onRowClick(item) {
  // TODO: navigate or open details modal
  console.log('row clicked', item)
}

async function downloadFile(fileId) {
  try {
    const res = await fetch(`/api/File/download/${fileId}`)
    if (res.ok) {
      const blob = await res.blob()
      const url = window.URL.createObjectURL(blob)
      const a = document.createElement('a')
      a.href = url
      const contentDisposition = res.headers.get('Content-Disposition')
      const fileName = contentDisposition
        ? contentDisposition.split('filename=')[1]?.replace(/"/g, '')
        : `file_${fileId}.xml`
      a.download = fileName
      document.body.appendChild(a)
      a.click()
      document.body.removeChild(a)
      window.URL.revokeObjectURL(url)
    } else {
      alert('Failed to download file')
    }
  } catch (e) {
    console.error('Download error', e)
    alert('Error downloading file')
  }
}

async function sendEmail(fileId) {
  if (!confirm('Send this file via email?')) return
  try {
    const res = await fetch(`/api/File/email/${fileId}`, { method: 'POST' })
    if (res.ok) {
      alert('Email queued successfully')
    } else {
      alert('Failed to queue email')
    }
  } catch (e) {
    console.error('Email error', e)
    alert('Error sending email')
  }
}
</script>

<template>
  <div class="container pt-4">
    <h3>Generated Files Repository</h3>

    <hr />

    <p class="text-muted">
      Below are the files generated by reconciliation runs. Click a row to view file details.
    </p>

    <div class="mb-3">
      <label class="form-label">Filter By:</label>
      <!-- BaseTable will render the configured filters (including a date picker) -->
    </div>

    <BaseTable
      :columns="columns"
      :items="items"
      :showSearch="true"
      :showPagination="true"
      :pageSizeOptions="[10,25,50]"
      :filters="filters"
      :rowClickable="true"
      @row-click="onRowClick"
    >
      <template #actions="{ item }">
        <button @click.stop="downloadFile(item.id)" class="btn btn-sm btn-primary me-1" title="Download">
          <i class="bi bi-download"></i>
        </button>
        <button @click.stop="sendEmail(item.id)" class="btn btn-sm btn-success" title="Send Email">
          <i class="bi bi-envelope"></i>
        </button>
      </template>
    </BaseTable>
  </div>
</template>

<style scoped></style>
